"""Inital Migration

Revision ID: d6b8c8dad577
Revises: 
Create Date: 2022-03-01 23:57:41.411190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6b8c8dad577'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('address1', sa.String(length=256), nullable=False),
    sa.Column('address2', sa.String(length=256), nullable=True),
    sa.Column('city', sa.String(length=256), nullable=False),
    sa.Column('county', sa.String(length=256), nullable=True),
    sa.Column('country', sa.String(length=256), nullable=False),
    sa.Column('postcode', sa.String(length=10), nullable=True),
    sa.Column('datetime_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('datetime_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('datetime_posted', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('datetime_joined', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('article', sa.Column('datetime_posted', sa.DateTime(timezone=True), nullable=True))
    op.add_column('article', sa.Column('datetime_created', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('article', 'date')
    op.add_column('writer', sa.Column('datetime_joined', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('writer', 'datetime_joined')
    op.add_column('article', sa.Column('date', sa.DATETIME(), nullable=True))
    op.drop_column('article', 'datetime_created')
    op.drop_column('article', 'datetime_posted')
    op.drop_table('subscription')
    op.drop_table('events')
    # ### end Alembic commands ###
