"""empty message

Revision ID: e7099b69d677
Revises: d6b8c8dad577
Create Date: 2022-03-02 18:51:29.103271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7099b69d677'
down_revision = 'd6b8c8dad577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('address1', sa.String(length=256), nullable=False),
    sa.Column('address2', sa.String(length=256), nullable=True),
    sa.Column('city', sa.String(length=256), nullable=False),
    sa.Column('county', sa.String(length=256), nullable=True),
    sa.Column('country', sa.String(length=256), nullable=False),
    sa.Column('postcode', sa.String(length=10), nullable=False),
    sa.Column('datetime_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('datetime_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('datetime_posted', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('events')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.VARCHAR(length=256), nullable=False),
    sa.Column('address1', sa.VARCHAR(length=256), nullable=False),
    sa.Column('address2', sa.VARCHAR(length=256), nullable=True),
    sa.Column('city', sa.VARCHAR(length=256), nullable=False),
    sa.Column('county', sa.VARCHAR(length=256), nullable=True),
    sa.Column('country', sa.VARCHAR(length=256), nullable=False),
    sa.Column('postcode', sa.VARCHAR(length=10), nullable=True),
    sa.Column('datetime_end', sa.DATETIME(), nullable=True),
    sa.Column('datetime_start', sa.DATETIME(), nullable=True),
    sa.Column('datetime_posted', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('event')
    # ### end Alembic commands ###
